# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec17bd9f209364b21be056b16eb7ccf4a96fe4c0aa9e9a4f081073db03905dbb5b7704f0487e0a66c6e88d1c5ac7a24dea13f782fb0bd6ba13abc15006c45e7d

test:
  secret_key_base: 7b106f9993bad4c6966ccaf0296839f9352ff3bc203497942038328ac78be130fe0c6d1337ee75ab8e0654091c722993dc78c93447d458e038a8d3a386e17964

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
